### PR TITLE
Next

### PR DESCRIPTION
**Pull request by vrozenfe**
The following series was created to reflect the leates changes that happened in virtio-win
building process and virtio-win installer code

### CODE REVIEW

**Comment by Gal-Zaidman** [comment]
looks good to me

**Comment by crobinso** [comment]
Thanks Gal. @vrozenfe please update this to use Gal's mentioned commit and then I will give it a try

**Comment by vrozenfe** [comment]
Here is a new one
https://github.com/crobinso/virtio-win-pkg-scripts/pull/29

**Comment by crobinso** [comment]
FWIW if you `git push --force` on top of the branch used to submit the PR, the PR gets updated, submitting a new one isn't necessary. But let's follow up in #29

**Pull request closed without merging**
